/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
 * Sistema: Control de Gastos Personales
 * Autor: Rodrigo Hernandez Perez
 * Descripción: Formulario principal para registrar,
 * buscar, actualizar y eliminar ingresos y gastos.
 */
package vistaFront;

import controlGastos.ControlGastos;
import modelo.Movimientos;
import modelo.Ingresos;
import modelo.Gastos;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ligoh
 */
public class frmControlGastos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmControlGastos.class.getName());

    /**
     * Creates new form frmControlGastos
     */
    private ControlGastos control;
    private DefaultTableModel modeloTabla;
    
    public frmControlGastos() {
        initComponents();
        lblAutor.setText("Desarrollado por: Rodrigo Hernandez Perez");
        control = new ControlGastos(10, 0);
        actualizarTotales();
        modeloTabla = (DefaultTableModel) tblMovimientos.getModel();

        cmbTipo.removeAllItems();
        cmbTipo.addItem("Ingreso");
        cmbTipo.addItem("Gasto");
    }
    
    private void limpiarCampos() {
        txtDescripcion.setText("");
        txtCantidad.setText("");
        txtFecha.setText("");
        cmbTipo.setSelectedIndex(0);
    }
    //metodo para que se muestre los movimientos almacenados
    private void cargarTabla() {

         modeloTabla.setRowCount(0);

        for (int i = 0; i < control.contarMovimientos(); i++) {

            Movimientos m = control.obtenerMovimiento(i);

            String tipo;

            if (m instanceof Ingresos) {
                tipo = "Ingreso";
            } else {
                tipo = "Gasto";
            }

            modeloTabla.addRow(new Object[]{
                m.getDescripcion(),
                m.getCantidad(),
                m.getFecha(),
                tipo
            });
        }

        actualizarTotales();
    }
    private void actualizarTotales() {

        lblIngresos.setText(
                "Total ingresos: $" + control.calcularTotalIngresos()
        );

        lblGastos.setText(
                "Total gastos: $" + control.calcularTotalGastos()
        );

        lblSaldo.setText(
                "Saldo: $" + control.calcularSaldo()
        );

        lblCantidadMovi.setText(
                "Movimientos: " + control.contarMovimientosRecursivo()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        lblIngresos = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblCantidadMovi = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        txtSaldoInicial = new javax.swing.JTextField();
        btnSaldoInicial = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Fecha");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Gasto" }));

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripción", "Cantidad", "Fecha", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMovimientos.getTableHeader().setReorderingAllowed(false);
        tblMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMovimientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMovimientos);

        lblIngresos.setForeground(new java.awt.Color(0, 153, 51));
        lblIngresos.setText("Total ingresos");

        lblGastos.setForeground(new java.awt.Color(255, 0, 0));
        lblGastos.setText("Total gastos");

        lblSaldo.setForeground(new java.awt.Color(0, 153, 0));
        lblSaldo.setText("saldo");

        lblCantidadMovi.setText("Movimientos");

        lblSaldoInicial.setText("Agregar Saldo Inicial");

        btnSaldoInicial.setBackground(new java.awt.Color(204, 204, 204));
        btnSaldoInicial.setText("Establecer Saldo Inicial");
        btnSaldoInicial.addActionListener(this::btnSaldoInicialActionPerformed);

        lblTitulo.setBackground(new java.awt.Color(0, 51, 102));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lblTitulo.setText("Sistema de Control de Ingresos y Gastos");

        lblAutor.setText("autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCantidad)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFecha)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaldoInicial)
                                .addGap(46, 46, 46))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblCantidadMovi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGastos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo)
                    .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(36, 36, 36)
                .addComponent(lblSaldoInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaldoInicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadMovi)
                .addGap(18, 18, 18)
                .addComponent(lblAutor)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        txtDescripcion.getAccessibleContext().setAccessibleName("txtDescripcion");
        txtCantidad.getAccessibleContext().setAccessibleName("txtCantidad");
        txtFecha.getAccessibleContext().setAccessibleName("txtFecha");
        lblCantidad.getAccessibleContext().setAccessibleName("lblCantidad");
        lblTipo.getAccessibleContext().setAccessibleName("lblTipo");
        lblTipo.getAccessibleContext().setAccessibleDescription("");
        btnRegistrar.getAccessibleContext().setAccessibleName("btnRegistrar");
        btnBuscar.getAccessibleContext().setAccessibleName("btnBuscar");
        btnEliminar.getAccessibleContext().setAccessibleName("btnEliminar");
        btnActualizar.getAccessibleContext().setAccessibleName("btnActualizar");

        getAccessibleContext().setAccessibleName("cmbTipo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {

            String descripcion = txtDescripcion.getText();
            float cantidad = Float.parseFloat(txtCantidad.getText());
            String fecha = txtFecha.getText();
            String tipo = cmbTipo.getSelectedItem().toString();

            Movimientos m;

            if (tipo.equals("Ingreso")) {
                m = new Ingresos(descripcion, cantidad, fecha);
            } else {
                m = new Gastos(descripcion, cantidad, fecha);
            }

            control.registrarMovimiento(m);

            cargarTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Movimiento registrado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String descripcion = txtDescripcion.getText();

        Movimientos m = control.buscarMovimiento(descripcion);

        if (m != null) {

            txtCantidad.setText(String.valueOf(m.getCantidad()));
            txtFecha.setText(m.getFecha());

            if (m instanceof Ingresos) {
                cmbTipo.setSelectedItem("Ingreso");
            } else {
                cmbTipo.setSelectedItem("Gasto");
            }

            JOptionPane.showMessageDialog(this, "Movimiento encontrado");

        } else {

            JOptionPane.showMessageDialog(this, "No se encontró");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String descripcion = txtDescripcion.getText();

        boolean eliminado = control.eliminarMovimiento(descripcion);

        if (eliminado) {

            cargarTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Movimiento eliminado");

        } else {

            JOptionPane.showMessageDialog(this, "No se encontró el movimiento");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String descripcion = txtDescripcion.getText();

        try {

            float cantidad = Float.parseFloat(txtCantidad.getText());
            String fecha = txtFecha.getText();
            String tipo = cmbTipo.getSelectedItem().toString();

            Movimientos nuevo;

            if (tipo.equals("Ingreso")) {
                nuevo = new Ingresos(descripcion, cantidad, fecha);
            } else {
                nuevo = new Gastos(descripcion, cantidad, fecha);
            }

            boolean actualizado = control.actualizarMovimiento(descripcion, nuevo);

            if (actualizado) {

                cargarTabla();
                limpiarCampos();

                JOptionPane.showMessageDialog(this, "Movimiento actualizado");

            } else {

                JOptionPane.showMessageDialog(this, "No se encontró el movimiento");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMovimientosMouseClicked
        int fila = tblMovimientos.getSelectedRow();

        if (fila >= 0) {

            txtDescripcion.setText(
                    tblMovimientos.getValueAt(fila, 0).toString()
            );

            txtCantidad.setText(
                    tblMovimientos.getValueAt(fila, 1).toString()
            );

            txtFecha.setText(
                    tblMovimientos.getValueAt(fila, 2).toString()
            );

            cmbTipo.setSelectedItem(
                    tblMovimientos.getValueAt(fila, 3).toString()
            );
        }
    }//GEN-LAST:event_tblMovimientosMouseClicked

    private void btnSaldoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoInicialActionPerformed
        try {

            float saldo = Float.parseFloat(txtSaldoInicial.getText());

            control.establecerSaldoInicial(saldo);

            actualizarTotales();

            JOptionPane.showMessageDialog(
                this,
                "Saldo inicial establecido correctamente"
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );
        }
    }//GEN-LAST:event_btnSaldoInicialActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmControlGastos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSaldoInicial;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadMovi;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
